### ISSUE TITLE
while I ran 'run_gen.py --no-tmp-cleaner -o ./test --target gcc' on a linux machine

### ISSUE THREAD

**Issue by Codymap** [intel/yarpgen#164]
while I ran 'run_gen.py --no-tmp-cleaner -o ./test --target gcc' on a linux machine, I still cannt get ok TC files saving , there only have compfail and runfail in /test/result/gcc. Can I get the files which status are ok?

**Comment by Vsevolod-Livinskij** [comment]
It is not a typical application case, so  ``run_gen.py`` doesn't support this by default.

The easiest way to get them is to use a workaround.
1. Generate random seeds (64-bit _**positive**_ number) and write them to a file (e.g., ``seeds.txt``). They have to be separated by a space or a new line
2. Pass them to ``run_gen.py`` to test which are correct: ``./run_gen.py --seeds seeds.txt``
3. The failed seeds will be stored in the ``testing/result`` directory and printed at the end of the execution of ``run_gen.py`` under ``FAILED SEEDS`` section
4. Exclude failed seeds from the ``seeds.txt`` file. After that, the remaining seeds will correspond to tests that don't trigger a compiler error
5. For each of them, use ``yarpgen`` (the binary can be found at the top of the build directory) to generate a test: ``./yarpgen -s YYY``. You can also tell it to save files to a pre-existing folder with ``-o`` argument: ``./yarpgen -s YYY -o YYY``

Please let me know if the suggested solution doesn't work or if you have any other questions.

**Comment by Codymap** [comment]
Thank you very much ! This is very helpful for me, the problem has be solved.

**Comment by Codymap** [comment]
Sorry about borthering you so much. there are two problems I cann't solved. The fist one is: I donn't know how to use Test_Makefile in fail foder to regenerate the fail seed test case; The second is I'm not sure whether can this Fuzzer test compiler based on DSP chip designed by ourselves. Becase I donn't know the algorithm of checking runfail bugs. Our compiler is not like the other common compilers, we compiler c/cpp files on DSP chip or run xxx.out/xxx.dat files on simulator we designed. If it is necessary to me to read the source code of checking runfail bugs in  this Fuzzer? So we can add the algorithm in our simulator or somthing else.

**Comment by Codymap** [comment]
Our test solutuion is if the test case can pass gcc or clang, it will be tested by our DSP compiler. We benchmarked GCC /Clang compilers in opt O0 and O2. So we compiler these passed testcase on GCC/Clang and our compiler, just like CSMITH to do cross-compilering. As YARPGEN has no output result, I'm not sure the Fuzzer can test DSP compiler. In my experiences, when I test our DSP compiler, there are a certain amount testcase which the output hash value are diferent from GCC/Clang.
