### ISSUE TITLE
How to generate C codes

### ISSUE THREAD

**Issue by khagankhan** [intel/yarpgen#178]
How can I generate the C codes? Just the C codes themselves in a file, or stdout, etc? I would like to refer your code generator. All I need is just the valid, random C codes. How can I access it?

Great tool!

-Thanks

**Comment by Vsevolod-Livinskij** [comment]
After you [build](https://github.com/Vsevolod-Livinskij/yarpgen#building-and-running) `yarpgen`, you can use the `--std` flag to select target language: ``./yarpgen --std=c``.

It will create `func.c` file with the test function, `init.h` file with external variables declaration, and `driver.c` file with the boilerplate code required to run the test. They can be optionally placed in the output folder if you pass ``-o out/`` parameter.

Thank you! Please let us know if you manage to find bugs with yarpgen, it helps us to publish papers and keeps us motivated.
