### ISSUE TITLE
What dependencies are needed to compile yarpgen

### ISSUE THREAD

**Issue by bettychen1** [intel/yarpgen#184]
my cmake version is 3.22.1
when trying to make my project，the following error occurs
git clone -q --branch=main https://github.com/intel/yarpgen.git /home/appveyor/projects/yarpgen
git checkout -qf 29a67b2def8b2031b8f3ae033ba45675d216a5ab
mkdir build && cd build
cmake ..
make -j4

[  4%] Building CXX object src/CMakeFiles/yarpgen_lib.dir/emit_policy.cpp.o
[  8%] Building CXX object src/CMakeFiles/yarpgen_lib.dir/data.cpp.o
[ 12%] Building CXX object src/CMakeFiles/yarpgen_lib.dir/context.cpp.o
[ 16%] Building CXX object src/CMakeFiles/yarpgen_lib.dir/expr.cpp.o
[ 20%] Building CXX object src/CMakeFiles/yarpgen_lib.dir/gen_policy.cpp.o
yarpgen/src/expr.cpp: In member function ‘virtual yarpgen::Expr::EvalResType yarpgen::ReductionExpr::evaluate(yarpgen::EvalCtx&)’:
yarpgen/src/expr.cpp:2701:67: error: cannot deduce template arguments for ‘plus’ from ()
                                     ctx.total_iter_num, std::plus()));
                                                                   ^
yarpgen/src/expr.cpp:2706:68: error: cannot deduce template arguments for ‘minus’ from ()
                                     ctx.total_iter_num, std::minus()));
                                                                    ^
yarpgen/src/expr.cpp:2711:73: error: cannot deduce template arguments for ‘multiplies’ from ()
                                     ctx.total_iter_num, std::multiplies()));
                                                                         ^
yarpgen/src/expr.cpp:2716:70: error: cannot deduce template arguments for ‘divides’ from ()
                                     ctx.total_iter_num, std::divides()));
                                                                      ^
yarpgen/src/expr.cpp:2721:70: error: cannot deduce template arguments for ‘modulus’ from ()
                                     ctx.total_iter_num, std::modulus()));
                                                                      ^
yarpgen/src/expr.cpp:2734:70: error: cannot deduce template arguments for ‘bit_xor’ from ()
                                     ctx.total_iter_num, std::bit_xor()));
                                                                      ^
[ 25%] Building CXX object src/CMakeFiles/yarpgen_lib.dir/hash.cpp.o
src/CMakeFiles/yarpgen_lib.dir/build.make:117: recipe for target 'src/CMakeFiles/yarpgen_lib.dir/expr.cpp.o' failed
make[2]: *** [src/CMakeFiles/yarpgen_lib.dir/expr.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:107: recipe for target 'src/CMakeFiles/yarpgen_lib.dir/all' failed
make[1]: *** [src/CMakeFiles/yarpgen_lib.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Vsevolod-Livinskij** [comment]
Could you please tell me which OS and compiler you use?

I've never seen this error. 
I usually build YARPGen on Ubuntu 22.04.2 LTS with system-provided gcc version 11.3.0.  You can also check other tested configurations in our CI builds [here](https://ci.appveyor.com/project/webmasterintel/yarpgen/builds/47334589).
