### ISSUE TITLE
Possible UB with right shifts

### ISSUE THREAD

**Issue by maroneze** [intel/yarpgen#58]
I just tried yarpgen for C program generation, and it is generating several programs that are perfectly fine, however some of them seem to contain undefined behavior related to bitwise shifts.

From yarpgen's README, I understand that implementation-defined behavior is fine, but not undefined behavior.

I am considering in particular the excerpt below from the C11 standard:

> #### 6.5.7 Bitwise shift operators
> 
> 3 If the value of the right operand is negative or is greater than or equal to the width of the promoted left operand, the behavior is undefined.

In some of the generated programs, I am getting such cases, for instance in this very long statement:

    tf_0_var_217 = (long int) ((+(((int) (tf_0_array_2 [0].member_3_0.member_2_0)) && (!(!((int)
     (tf_0_array_7 [4].member_3_8.member_1_3)))))) - ((int) ((!((!((int) (tf_0_array_2 
    [0].member_3_1))) && (!((int) (tf_0_array_7 [4].member_3_9.member_2_3))))) == ((int) (((long int) 
    (~(-((int) (tf_0_array_5 [3].member_3_6.member_2_4.member_1_1))))) < ((((tf_0_array_3 [8]) - 
    (tf_0_array_5 [2].member_3_0.member_2_1)) + (9223372036854775807L)) >> ((tf_0_array_1 [0]) - 
    (846022147311755129L))))))));

The shift operator is at the end. The value of `tf_0_array_1[0]` is `446783363` at this point, so `446783363 - 846022147311755129L` results in a negative value for the RHS operand of the shift, triggering UB.

Could you please confirm if this situation may indeed arise, or if there are mechanisms to prevent it? I may have incorrectly analyzed the program if that is the case.

I am using `yarpgen --std=c11` to generate my programs.

**Comment by Vsevolod-Livinskij** [comment]
Yarpgen should produce UB-free code by design, so if you get UB it is obviously a bug inside the generator. Can you please provide the commit's hash and yarpgen's seed, where you get such result?

**Comment by maroneze** [comment]
Commit: d0e751682c861299eb963cd0a4a1b75ffcc484bd

After running `make`, I created a `tmp` folder then ran `./yarpgen -d tmp --std=c11 -s 123456` (I lost the seed of my previous example, so I just used another one here).

It outputs `/*SEED 12_123456*/` and, in `func.c:20`, there is an expression with a right shift by a large value:

    (tf_0_var_38) >> ((tf_0_struct_obj_5.member_4_4) - (337668908229336354UL)

I can try to find a different seed with a simpler expression, if that helps.

**Comment by Vsevolod-Livinskij** [comment]
Please note that yarpgen by-default generates code for 64-bit platforms (so it treats long int as long long int). If you want to generate code for 32-bit platform, use `yarpgen -m 32`.
I think that it might be the root of the problem that you observe.

**Comment by maroneze** [comment]
Indeed, that must have been the cause. I inadvertently overwrote the original files and the terminal output, but the fact that I have not been able to reproduce it indicates it must have been a misconfiguration related to 32 bits. Now that I properly configured my analysis, I no longer encounter any cases of UB.

Sorry for the report, and thanks for the information.

**Comment by Vsevolod-Livinskij** [comment]
I'm glad that now everything works fine! Feel free to ask any questions or leave a response. 

P.S. It might be a good idea to save seeds, because they allow anyone to reproduce generator run and all of the results.

**Comment by maroneze** [comment]
Well, actually, after running a few more hundred tests, this time properly considering 64 bits, I got another case.

Just to give some context: I'm running Frama-C on programs generated by yarpgen to check for issues in Frama-C (we did it in the past with Csmith, and found issues both in Frama-C and in Csmith). So if you could please check the cases mentioned below; if they're fine, then it's Frama-C's fault.

The case I got now is with seed `12_2745586521`, in `func.c:5315`, a left shift with a negative LHS value. I can give extra information provided by Frama-C, if that may help.

Incidentally, Frama-C also reported a signed overflow related to a multiplication in another test case, seed `12_410933379`, in `func.c:328`.

**Comment by dbabokin** [comment]
Is this code actually executed? In the dead branches I think there might be the code, which looks like UB and is actual UB. But it's assumed to be never executed.

We run the generator with UBSan a lot and I think it easily catches cases with UB in shifts.

**Comment by dbabokin** [comment]
I can't reproduce. These seeds produce different program for me. What is "yarpgen --version" reports? On what platform are you building it? What compiler did you use?

**Comment by maroneze** [comment]
Here's what I did for the first program (with the left shift):

    $ ./yarpgen --version
    yarpgen version 1.2 (build commit d0e751682c861299 on 2018:02:21)
    $ mkdir bug
    $ ./yarpgen -s 2745586521 -d bug1 --std=c11
    # using Frama-C Sulfur
    $ frama-c -machdep gcc_x86_64 -val -value-msg-key=-initial-state,-final-states bug1/*.c
    [kernel] Parsing bug1/driver.c (with preprocessing)
    [kernel] Parsing bug1/func.c (with preprocessing)
    [value] Analyzing a complete application starting at main
    [value] Computing initial state
    [value] Initial state computed
    bug1/func.c:5315:[value] warning: invalid LHS operand for left shift.
        assert 0 ≤ (long)(4L + (long)((int)(-253995373)));
    [value] done for function main
    bug1/func.c:5315:[value] assertion 'Value,shift' got final status invalid.

The fact that Frama-C reports the assertion as invalid means that (1) it considers the code as executable, and (2) at this point, the only possible behavior is undefined.

I am not using any compiler, just preprocessing the code with gcc and then Frama-C's semantics interpret the program according to the C standard. It is possible that Frama-C's semantics is invalid, so I'm thinking of other ways to check it.

Note that if I manually add a `printf` just before line 5315, then compile and run the program, my `printf` is executed, so the code is not dead. By the way, I just noticed that simply compiling the generated code with gcc (7.3.1) leads to several warnings `warning: overflow in implicit constant conversion [-Woverflow]` (though not in line 5315).

**Comment by Vsevolod-Livinskij** [comment]
Yarpgen produces next code:
`((((((int) (((long int) (-400607039)) / (5522118133451740430L))) ? ((4L) + ((long int) (-253995373))) : ((long int) ((-2) - (-400607039))))) << ((int) (((long int) (((-253995373) + (2147483647)) << ((4L) - (4L)))) != (-9007199254740992L)))) - (801214039L))`

LHS of shift expression is `(((int) (((long int) (-400607039)) / (5522118133451740430L))) ? ((4L) + ((long int) (-253995373))) : ((long int) ((-2) - (-400607039))))`
Condition of the ternary operator is equal to 0, so the value of the whole expression is `(long int) ((-2) - (-400607039)) = 400607037L`.
Value of the RHS of shift expression is 1, so overall it is valid shift operation `400607037L << 1`.

Both manual step-by-step evaluation of the expression and UB-sanitizer shows that line 5315 is correct. I think that it is a Frama-C fault.

Also, Yarpgen produces totally UB-free code (even if it not executed). The behavior, described by Dmitry, is planned in future versions.

**Comment by maroneze** [comment]
Thanks a lot for taking a look at it, I'll check the issue with Frama-C! It's likely the same issue in the signed overflow example as well, so not worth looking into it.

**Comment by Vsevolod-Livinskij** [comment]
If it is actually a bug in Frama-C, we would be happy to add it to our collection of detected errors. Also, feel free to commit new found bugs to [bugs.rst](https://github.com/intel/yarpgen/blob/master/bugs.rst), it helps us a lot!

**Comment by dbabokin** [comment]
We've found the whole bunch of bugs in UBSan implementation in GCC. So I wouldn't be surprised if we triggered some bugs in Frama-C as well. Please keep us posted on this. And thanks for trying out YARPGen.

**Comment by maroneze** [comment]
Between yesterday and today I ran several thousand tests to check for other issues, in both 32 and 64-bit, and nothing else was found.

YARPGen helped us identify an issue with a rare case of constant folding with type conversion, division and ternary operator combined.

However, since Frama-C is not a compiler, and the issue is listed only in our non-public bug tracker, I don't know how it should be added to `bugs.rst`, but feel free to do it as you see fit.

Thank you for the analysis and the tool, it is very straightforward to use.

**Comment by maroneze** [comment]
Between yesterday and today I ran several thousand tests to check for other issues, in both 32 and 64-bit, and nothing else was found.

YARPGen helped us identify an issue with a rare case of constant folding with type conversion, division and ternary operator combined.

However, since Frama-C is not a compiler, and the issue is listed only in our non-public bug tracker, I don't know how it should be added to `bugs.rst`, but feel free to do it as you see fit.

Thank you for the analysis and the tool, it is very straightforward to use.

Oh, by the way, I heard of it after John Regehr tweeted about it; just to let you know.

**Comment by dbabokin** [comment]
Thanks for the heads up. I'll mention the bug in our README. Also, any other feedback is very welcome. There are still a lot of features that are not implemented and feedback will help understand what is more relevant for other projects.
