### ISSUE TITLE
build failure on Mac OS X

### ISSUE THREAD

**Issue by emeryberger** [intel/yarpgen#59]
Compilation currently fails.

> $ clang++ --version
> Apple LLVM version 9.0.0 (clang-900.0.39.2)
> Target: x86_64-apple-darwin17.4.0
> Thread model: posix
> InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
> 
> $ make
> /bin/mkdir -p objs
> clang++ -O3 -std=c++14 -Wall -Wpedantic -Werror -DBUILD_DATE="\"2018:02:21\"" -DBUILD_VERSION="\"commit d0e751682c861299\"" -o objs/main.o -c src/main.cpp
> clang++ -O3 -std=c++14 -Wall -Wpedantic -Werror -DBUILD_DATE="\"2018:02:21\"" -DBUILD_VERSION="\"commit d0e751682c861299\"" -o objs/type.o -c src/type.cpp
> clang++ -O3 -std=c++14 -Wall -Wpedantic -Werror -DBUILD_DATE="\"2018:02:21\"" -DBUILD_VERSION="\"commit d0e751682c861299\"" -o objs/variable.o -c src/variable.cpp
> clang++ -O3 -std=c++14 -Wall -Wpedantic -Werror -DBUILD_DATE="\"2018:02:21\"" -DBUILD_VERSION="\"commit d0e751682c861299\"" -o objs/expr.o -c src/expr.cpp
> src/expr.cpp:786:52: error: no matching member function for call to 'get_rand_value'
>                 uint64_t const_val = rand_val_gen->get_rand_value(0UL, max_sht_val);
>                                      ~~~~~~~~~~~~~~^~~~~~~~~~~~~~
> src/gen_policy.h:62:11: note: candidate template ignored: deduced conflicting types for
>       parameter 'T' ('unsigned long' vs. 'unsigned long long')
>         T get_rand_value (T from, T to) {
>           ^
> 1 error generated.
> make: *** [objs/expr.o] Error 1

**Comment by emeryberger** [comment]
Fix: in two places in `expr.cpp`, replace `get_rand_value(0UL...` with `get_rand_value(0ULL...`.

**Comment by dbabokin** [comment]
Correct fix is to use "uint64_t(0)". Otherwise Linux build will be broken.
